services:

  User.profiles.ProfileRepository:
    class: ../../../../../Contexts/User/Profiles/infrastructure/MongoProfileRepository
    arguments: [ '@Shared.ConnectionManager' ]

  User.profiles.ProfileCreator:
    class: ../../../../../Contexts/User/Profiles/application/ProfileCreator
    arguments: [ '@User.profiles.ProfileRepository', '@Shared.EventBus' ]

  User.profiles.CreateProfileCommandHandler:
    class: ../../../../../Contexts/User/Profiles/application/CreateProfileCommandHandler
    arguments: [ '@User.profiles.ProfileCreator' ]
    tags:
      - { name: 'commandHandler' }
