imports:
  - { resource: ./application.yaml }

services:
  User.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: [ '@Shared.ConnectionManager' ]

  Shared.EventBus:
    class: ../../../../Contexts/Shared/infrastructure/Bus/Event/InMemory/InMemorySyncEventBus
    arguments: [ ]
