imports:
  - { resource: ./application.yaml }

services:

  Recommendation.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/Arranger/elastic/ElasticEnvironmentArranger
    arguments: [ '@Shared.ElasticConnectionManager', '@Recommendation.suggestions.ElasticConfig' ]

  Shared.EventBus:
    class: ../../../../Contexts/Shared/infrastructure/Bus/Event/InMemory/InMemorySyncEventBus
    arguments: [ ]
